---
title: "Bio381"
author: "Jessica Cole"
date: "August 29, 2018"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: vignette

    
  
    
  
---


# My homeworks

##Hmw1

* [Week 1 - Getting to Know Github](introduction.html)

* [Week 2 - Exploring on Paper](Pre-graphs.html)

* [Week 3 - Beamer Presenation](BeamerPresentation.pdf)

* [Week 4 - Vectors in R and Regular Expressions](VectorsinRandRegularExpressions.html) 

* [Week 5 - Manipulating data using dplyr](Dplyrhw.html)

* [Week 6 - Data Distributions](Datadistributions.html)

* [Week 6 - Data Distributions continued](simulatedcatdata.html)

* [Week 7 - Simulating Fake data](CreatingFakeDataSetstoExploreHypotheses.html)

* [Week 8 - Organizing Code with structured Programming](OrganizingCode.html)

* [Week 9 & 10 - For loops and randomization tests](RandomizationTestHW.html)

* [Week 11 - Advanced GGPloting](advancedggplot.html)

* [Week 12 - Final Presentation](shinyscript.html)

* [Final Presentation-Rmd File](shinyscript.Rmd)












